### ISSUE TITLE
v1.2.0 checklist

### ISSUE THREAD

**Issue by Sauceke** [Sauceke/LoveMachine#24]
- [x] Acceptably accurate syncing for every Receive and Masturbation animation
- [x] Feature freeze
- [x] Update readme
  - [x] new features and settings
  - [x] installation
  - [x] full list of supported devices
- [x] Bump plugin version in code (forgot this last time)
- [x] QA testing
  - [x] have fun
  - [x] have fun with 2 devices
  - [x] check vibration
- [x] ~~Find a script to auto generate changelog~~ gave up
- [x] Run release job
- [x] Check release job output

**Comment by Sauceke** [comment]
🥳
