### ISSUE TITLE
v2.0.0 checklist

### ISSUE THREAD

**Issue by Sauceke** [Sauceke/LoveMachine#45]
The scope of the project has changed and the name has to change too, so this will be a major release.

- [x] #46
- [x] #48
- [x] Feature freeze
- [x] Bump assembly version
- [x] Update release job
  - [x] Put output for each game into its own zip
- [x] QA Testing
  - [x] KK (stroker, vibe)
  - [x] HS2 (stroker, vibe)
- [x] Update readme
  - [x] HS2 support
  - [x] new syncing method and its quirks
  - [x] finalize JP version
- [x] Run release job
- [x] Check release job output

**Comment by Sauceke** [comment]
🥳
